## this is just an experiment. Do not try this at home.
## This is a local docker-compose file for running the application in a local environment.

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    working_dir: /app
    environment:
      - NODE_ENV=local
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=cart-db
  
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cart-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: